"""rename department

Revision ID: dedc5e9c5cba
Revises: c902d463b627
Create Date: 2025-09-14 15:56:37.899954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedc5e9c5cba'
down_revision = 'c902d463b627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
